Type: Jupyter Notebook Extension
Name: Snippets Menu
Link: readme.md
Description: Add customizable menu item to insert code and markdown snippets.  Comes with extensive defaults for popular python modules.
Main: main.js
Compatibility: 4.x
